SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN ( SELECT FLAVOR,SUM(TOTAL_ORDER) AS TOTAL_ORDER_JULY
       FROM JULY
       GROUP BY FLAVOR
     ) J
    ON J.FLAVOR= FH.FLAVOR
ORDER BY (J.TOTAL_ORDER_JULY+FH.TOTAL_ORDER) DESC 
LIMIT 3