SELECT CATEGORY,PRICE AS	MAX_PRICE,	PRODUCT_NAME
FROM FOOD_PRODUCT A
WHERE PRICE IN (SELECT MAX(B.PRICE) 
                FROM FOOD_PRODUCT B
                WHERE A.CATEGORY=B.CATEGORY
                AND B.CATEGORY IN ('과자', '국', '김치', '식용유')
                GROUP BY B.CATEGORY
               )
ORDER BY MAX_PRICE DESC